/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#3B0764',
          container: '#5B21B6',
          fixed: '#DDD6FE',
          'fixed-dim': '#C4B5FD',
          'on-container': '#7C3AED',
        },
        secondary: {
          DEFAULT: '#035cba',
          container: '#629dff',
          fixed: '#d7e3ff',
          'fixed-dim': '#abc7ff',
          'on-container': '#00346e',
        },
        tertiary: {
          DEFAULT: '#120026',
          container: '#33005c',
          fixed: '#f0dbff',
          'fixed-dim': '#ddb8ff',
          'on-container': '#b05fff',
        },
        surface: {
          DEFAULT: '#F8F9FC',
          bright: '#f8f9fc',
          dim: '#d9dadd',
          'container-lowest': '#ffffff',
          'container-low': '#F5F3FF',
          container: '#EDE9FE',
          'container-high': '#DDD6FE',
          'container-highest': '#C4B5FD',
          tint: '#7C3AED',
          variant: '#E9D5FF',
        },
        'on-surface': {
          DEFAULT: '#191c1e',
          variant: '#494551',
        },
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-background': '#191c1e',
        background: '#FFFFFF',
        outline: {
          DEFAULT: '#7b7582',
          variant: '#cbc4d3',
        },
        'lavender-tint': '#EDE9FE',
        'security-midnight': '#0A0118',
        verified: '#16A34A',
        'allow-emerald': '#009E5C',
        escalation: '#F59E0B',
        denied: '#DC2626',
        'reject-ruby': '#E11D48',
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
          'on-container': '#93000a',
        },
        'inverse-surface': '#2e3133',
        'inverse-on-surface': '#f0f1f4',
        'inverse-primary': '#d2bbff',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        outfit: ['Outfit', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        mono: ['Space Grotesk', '"JetBrains Mono"', 'monospace'],
        'label-mono': ['Space Grotesk', 'monospace'],
        'display-xl': ['Outfit', 'sans-serif'],
        'headline-lg': ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
      },
      boxShadow: {
        'ambient-1': '0px 4px 20px rgba(59, 7, 100, 0.07)',
        'ambient-2': '0px 12px 32px rgba(59, 7, 100, 0.12)',
        'ambient-glow': '0 0 0 2px #7C3AED',
        'glow-primary': '0 0 25px -5px rgba(59, 7, 100, 0.30)',
        'glow-emerald': '0 0 25px -5px rgba(22, 163, 74, 0.25)',
        'glow-rose': '0 0 25px -5px rgba(220, 38, 38, 0.25)',
        'glow-amber': '0 0 25px -5px rgba(245, 158, 11, 0.25)',
      },
      spacing: {
        'section-gap': '80px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        gutter: '24px',
      },
    },
  },
  plugins: [],
}
