/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#0e002b',
          container: '#2b0066',
          fixed: '#eaddff',
          'fixed-dim': '#d2bbff',
          'on-container': '#9677d5',
        },
        secondary: {
          DEFAULT: '#035cba',
          container: '#629dff',
          fixed: '#d7e3ff',
          'fixed-dim': '#abc7ff',
          'on-container': '#00346e',
        },
        tertiary: {
          DEFAULT: '#120026',
          container: '#33005c',
          fixed: '#f0dbff',
          'fixed-dim': '#ddb8ff',
          'on-container': '#b05fff',
        },
        surface: {
          DEFAULT: '#F8F9FC',
          bright: '#f8f9fc',
          dim: '#d9dadd',
          'container-lowest': '#ffffff',
          'container-low': '#f2f3f6',
          container: '#edeef1',
          'container-high': '#e7e8eb',
          'container-highest': '#e1e2e5',
          tint: '#6b4da8',
          variant: '#e1e2e5',
        },
        'on-surface': {
          DEFAULT: '#191c1e',
          variant: '#494551',
        },
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-background': '#191c1e',
        background: '#FFFFFF',
        outline: {
          DEFAULT: '#7b7582',
          variant: '#cbc4d3',
        },
        'lavender-tint': '#E9E1FF',
        'security-midnight': '#0A0118',
        verified: '#16A34A',
        'allow-emerald': '#009E5C',
        escalation: '#F59E0B',
        denied: '#DC2626',
        'reject-ruby': '#E11D48',
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
          'on-container': '#93000a',
        },
        'inverse-surface': '#2e3133',
        'inverse-on-surface': '#f0f1f4',
        'inverse-primary': '#d2bbff',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        outfit: ['Outfit', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        mono: ['Space Grotesk', '"JetBrains Mono"', 'monospace'],
        'label-mono': ['Space Grotesk', 'monospace'],
        'display-xl': ['Outfit', 'sans-serif'],
        'headline-lg': ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
      },
      boxShadow: {
        'ambient-1': '0px 4px 20px rgba(43, 0, 102, 0.04)',
        'ambient-2': '0px 12px 32px rgba(43, 0, 102, 0.08)',
        'ambient-glow': '0 0 0 2px #629dff',
        'glow-primary': '0 0 25px -5px rgba(43, 0, 102, 0.25)',
        'glow-emerald': '0 0 25px -5px rgba(22, 163, 74, 0.25)',
        'glow-rose': '0 0 25px -5px rgba(220, 38, 38, 0.25)',
        'glow-amber': '0 0 25px -5px rgba(245, 158, 11, 0.25)',
      },
      spacing: {
        'section-gap': '80px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        gutter: '24px',
      },
    },
  },
  plugins: [],
}
