"""Canonical Stable Facts Layer for AgentGuard Knowledge Pipeline.

Constructs authoritative canonical facts across Domains A through AE based strictly
on verified repository evidence. Explicitly flags facts requiring live backend tool queries.
"""

import hashlib

from backend.app.knowledge.models import (
    AuthorityType,
    CanonicalFactRecord,
    DomainCategory,
    DomainCoverageStatus,
    FreshnessStatus,
    KnowledgeUnit,
    SourceTier,
)

CANONICAL_FACTS_DATA: list[dict] = [
    # Domain A: Product Identity
    {
        "id": "fact_product_identity_definition",
        "domain": DomainCategory.A_PRODUCT_IDENTITY,
        "title": "AgentGuard System Definition",
        "fact_statement": "AgentGuard is the deterministic authorization firewall and trust layer that sits between autonomous AI agents and financial execution.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_5_SPEC_DOCS,
        "rationale": "Established in PRD.md §1 and Architecture.md §1.",
        "verified_sources": ["docs/PRD.md", "docs/Architecture.md"],
        "is_dynamic_tool_required": False,
    },
    # Domain B: Problem Statement
    {
        "id": "fact_problem_statement",
        "domain": DomainCategory.B_PROBLEM_STATEMENT,
        "title": "Autonomous AI Agent Financial Risk",
        "fact_statement": "Autonomous AI shopping agents can hallucinate prices, fall victim to prompt injection attacks, and cannot be safely trusted with direct credit cards or API keys.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_5_SPEC_DOCS,
        "rationale": "Documented in PRD.md §2 and threat_model.md §3.",
        "verified_sources": ["docs/PRD.md", "docs/threat_model.md"],
        "is_dynamic_tool_required": False,
    },
    # Domain C: Purpose
    {
        "id": "fact_system_purpose",
        "domain": DomainCategory.C_PURPOSE,
        "title": "AgentGuard Core Security Purpose",
        "fact_statement": "AgentGuard ensures that all financial mutations and agent spending proposals are mathematically verified against server-authoritative mandates, catalog pricing, and budget limits before payment execution.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_5_SPEC_DOCS,
        "verified_sources": ["docs/PRD.md", "backend/app/policy/engine.py"],
        "rationale": "Implemented via pure policy engine and atomic execute revalidation.",
        "is_dynamic_tool_required": False,
    },
    # Domain D: Architecture
    {
        "id": "fact_asymmetric_trust_architecture",
        "domain": DomainCategory.D_ARCHITECTURE,
        "title": "Asymmetric Trust Architecture",
        "fact_statement": "The system follows an asymmetric trust model where the AI agent is strictly an untrusted client with zero direct database or financial authority, while FastAPI and PostgreSQL serve as the trusted perimeter.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_5_SPEC_DOCS,
        "verified_sources": ["docs/Architecture.md", "backend/app/api/propose.py", "backend/app/api/execute.py"],
        "rationale": "Enforced by FastAPI router structure and PostgreSQL row locks.",
        "is_dynamic_tool_required": False,
    },
    # Domain E: Trust Model
    {
        "id": "fact_trust_boundary_separation",
        "domain": DomainCategory.E_TRUST_MODEL,
        "title": "Trust Boundary Separation",
        "fact_statement": "Candidate claims (claimed price, quantity, product ID) generated by an LLM are treated as untrusted proposals; authoritative price and merchant scope are derived strictly from server database state.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_5_SPEC_DOCS,
        "verified_sources": ["docs/threat_model.md", "backend/app/policy/engine.py"],
        "rationale": "Engine compares claimed_price vs authoritative product.price.",
        "is_dynamic_tool_required": False,
    },
    # Domain F: Security Invariants
    {
        "id": "fact_non_negotiable_invariants",
        "domain": DomainCategory.F_SECURITY_INVARIANTS,
        "title": "Server Re-Validation Invariant",
        "fact_statement": "Authorization is re-validated from scratch at execute time in /transaction/execute. A proposed ALLOW decision does not grant permanent execution rights if mandate status or catalog state changes.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["backend/app/api/execute.py", "docs/TRD.md"],
        "rationale": "Execute endpoint explicitly re-queries Mandate and Product under row locks.",
        "is_dynamic_tool_required": False,
    },
    # Domain G: Backend Architecture
    {
        "id": "fact_backend_stack",
        "domain": DomainCategory.G_BACKEND_ARCHITECTURE,
        "title": "Backend Technology Stack",
        "fact_statement": "The backend is implemented in Python 3.12+ using FastAPI, Pydantic v2 schemas, SQLAlchemy 2.0 ORM, and Uvicorn.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["backend/app/main.py", "backend/requirements.txt"],
        "rationale": "Directly inspectable from application entry point and package manifest.",
        "is_dynamic_tool_required": False,
    },
    # Domain H: Database Architecture
    {
        "id": "fact_database_acid_locks",
        "domain": DomainCategory.H_DATABASE_ARCHITECTURE,
        "title": "PostgreSQL ACID Row Locks",
        "fact_statement": "PostgreSQL is the single source of truth; concurrent spending races and double-spend attacks are prevented using SELECT ... FOR UPDATE row-level locking during execute.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["backend/app/api/execute.py", "backend/app/models/"],
        "rationale": "with_for_update() row locking implemented on Transaction and Mandate.",
        "is_dynamic_tool_required": False,
    },
    # Domain I: Policy Engine
    {
        "id": "fact_policy_engine_verdicts",
        "domain": DomainCategory.I_POLICY_ENGINE,
        "title": "Policy Engine Verdicts and Reason Codes",
        "fact_statement": "The policy engine is a pure Python function returning ALLOW, ESCALATE, or DENY with canonical reason codes: ALLOW, PRICE_MISMATCH, MERCHANT_MISMATCH, QUANTITY_INVALID, BUDGET_EXCEEDED, MANDATE_EXPIRED, MANDATE_REVOKED.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["backend/app/policy/engine.py", "backend/app/policy/reason_codes.py"],
        "rationale": "Pure Python evaluation without I/O side effects.",
        "is_dynamic_tool_required": False,
    },
    # Domain J: Mandates
    {
        "id": "fact_mandate_definition",
        "domain": DomainCategory.J_MANDATES,
        "title": "Mandate Spending Contract",
        "fact_statement": "A mandate establishes user spending limits: budget_total, budget_remaining, merchant_scope, max_transaction_amount, and expiration timestamp.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["backend/app/models/mandate.py", "backend/app/api/routes_mandate.py"],
        "rationale": "Schema definition in mandate model and routes.",
        "is_dynamic_tool_required": False,
    },
    # Domain K: Budgets (DYNAMIC TOOL REQUIRED)
    {
        "id": "fact_budget_live_query_requirement",
        "domain": DomainCategory.K_BUDGETS,
        "title": "Current Mandate Budget Live Query Requirement",
        "fact_statement": "The current remaining budget is dynamic operational state maintained authoritatively in PostgreSQL and must NEVER be retrieved from static knowledge. It must be fetched live via GET /mandate/{id}.",
        "authority": AuthorityType.DYNAMIC_LIVE_REQUIRED,
        "source_tier": SourceTier.TIER_1_LIVE_TOOL,
        "verified_sources": ["backend/app/api/routes_mandate.py"],
        "rationale": "Budget decrements atomically upon payment execution and increments upon payment decline.",
        "is_dynamic_tool_required": True,
        "required_tool": "get_mandate_status",
    },
    # Domain L: Transactions
    {
        "id": "fact_transaction_lifecycle",
        "domain": DomainCategory.L_TRANSACTIONS,
        "title": "Transaction State Machine",
        "fact_statement": "Transactions transition through PROPOSED -> ALLOWED/ESCALATED/DENIED -> EXECUTING -> SUCCESS/FAILED. Escalated transactions require human supervisor approval (/approve) to transition to ALLOWED.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["backend/app/api/propose.py", "backend/app/api/approve.py", "backend/app/api/execute.py"],
        "rationale": "Enforced by FastAPI route state validation.",
        "is_dynamic_tool_required": False,
    },
    # Domain M: Razorpay Integration
    {
        "id": "fact_razorpay_test_mode",
        "domain": DomainCategory.M_RAZORPAY_INTEGRATION,
        "title": "Razorpay Test-Mode Gateway Integration",
        "fact_statement": "Payment execution interacts with Razorpay test-mode API (in paise integers) with deterministic mock fallback when test credentials are not provided.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["backend/app/integrations/razorpay_client.py", "backend/app/services/payment_gateway.py"],
        "rationale": "RazorpayClient wrapper supports live sandbox API and mock fallback.",
        "is_dynamic_tool_required": False,
    },
    # Domain N: Agent Behavior
    {
        "id": "fact_agent_untrusted_proposal",
        "domain": DomainCategory.N_AGENT_BEHAVIOR,
        "title": "Shopping Assistant Untrusted Proposal Generation",
        "fact_statement": "The reference shopping agent uses Gemini (or deterministic heuristic fallback) to interpret natural user shopping prompts and generate candidate claim proposals.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["backend/app/integrations/gemini_client.py", "backend/app/api/routes_agent.py"],
        "rationale": "GeminiShoppingAgentClient formats JSON proposal for firewall ingestion.",
        "is_dynamic_tool_required": False,
    },
    # Domain O: Attack Scenarios (RECONCILED TAXONOMY)
    {
        "id": "fact_attack_scenarios_taxonomy",
        "domain": DomainCategory.O_ATTACK_SCENARIOS,
        "title": "Reconciled Attack Scenario Taxonomy",
        "fact_statement": "The Threat Simulation Lab UI provides 6 core interactive scenarios: (1) Happy Path [ALLOW], (2) Over-Budget Escalation [ESCALATE], (3) Price Tampering [DENY/PRICE_MISMATCH], (4) Replay Attack [DENY/REPLAY_DETECTED 409], (5) Safe Failure & Retry [PAYMENT_DECLINED -> ALLOW], (6) Mid-Session Revocation [DENY/MANDATE_REVOKED 403]. Additional policy engine scenarios include Merchant Scope Violation and Quantity Bound Validation.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["frontend/src/features/threat/ThreatSimulationLab.tsx", "docs/seed_data.md", "backend/tests/unit/test_policy_engine.py"],
        "rationale": "Matches both frontend interactive cards and backend automated test fixtures.",
        "is_dynamic_tool_required": False,
    },
    # Domain P: Audit Trail
    {
        "id": "fact_audit_trail_immutable",
        "domain": DomainCategory.P_AUDIT_TRAIL,
        "title": "Server-Generated Audit Trail",
        "fact_statement": "Every transaction proposal, policy decision, approval, execution, and decline is recorded by the server in an append-only audit ledger. Clients cannot inject or alter audit records.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["backend/app/services/audit_log.py", "backend/app/api/routes_audit.py"],
        "rationale": "log_audit_event() appends records under row lock on AuditChainState.",
        "is_dynamic_tool_required": False,
    },
    # Domain Q: SHA-256 Hash Chain
    {
        "id": "fact_sha256_hash_chain_formula",
        "domain": DomainCategory.Q_SHA256_HASH_CHAIN,
        "title": "Cryptographic SHA-256 Forward Hash Chain",
        "fact_statement": "Audit event integrity is secured via forward hash chaining where event_hash = SHA-256(prev_hash : event_type : actor : transaction_id : payload_hash). Genesis prev_hash is 64 zeros.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["backend/app/services/audit_log.py"],
        "rationale": "verify_audit_chain() verifies full chain integrity from genesis to head.",
        "is_dynamic_tool_required": False,
    },
    # Domain R: Frontend Architecture
    {
        "id": "fact_frontend_stack",
        "domain": DomainCategory.R_FRONTEND_ARCHITECTURE,
        "title": "Frontend Technology Stack",
        "fact_statement": "The frontend is built with React 18, Vite, TypeScript, TailwindCSS, React Router v7, and GSAP.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["frontend/package.json", "frontend/src/App.tsx"],
        "rationale": "Inspected from frontend package manifest and App router.",
        "is_dynamic_tool_required": False,
    },
    # Domain S: Navigation
    {
        "id": "fact_ui_navigation_routes",
        "domain": DomainCategory.S_NAVIGATION,
        "title": "Frontend Navigation Surfaces",
        "fact_statement": "The application routes across 4 primary views: '/' (Home/Story), '/live' (Live Protection), '/threats' (Threat Lab), and '/forensics' (Forensic Ledger), with global access to Developer Wire Telemetry and Conversational Assistant.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["frontend/src/App.tsx", "frontend/src/features/cockpit/SecurityCockpitHeader.tsx"],
        "rationale": "Router configuration in App.tsx.",
        "is_dynamic_tool_required": False,
    },
    # Domain T: Threat Simulation Lab
    {
        "id": "fact_threat_lab_surface",
        "domain": DomainCategory.T_THREAT_SIMULATION_LAB,
        "title": "Threat Simulation Lab Capabilities",
        "fact_statement": "The Threat Lab enables one-click adversarial scenario triggering, custom price/quantity attack injections, animated trust flow visualization, and live system kernel telemetry logs.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["frontend/src/features/threat/ThreatSimulationLab.tsx"],
        "rationale": "Component implementation in ThreatSimulationLab.tsx.",
        "is_dynamic_tool_required": False,
    },
    # Domain U: Live Protection
    {
        "id": "fact_live_protection_surface",
        "domain": DomainCategory.U_LIVE_PROTECTION,
        "title": "Live Protection Dual-Chamber Inspection",
        "fact_statement": "Live Protection provides a dual-chamber workspace pairing the untrusted shopping agent chat on the left against the server-authoritative firewall verdict hero and catalog truth on the right.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["frontend/src/features/defense/FirewallInspectionHero.tsx", "frontend/src/features/defense/UntrustedClientChamber.tsx"],
        "rationale": "LiveDefenseWorkspace layout in frontend.",
        "is_dynamic_tool_required": False,
    },
    # Domain V: Forensic Ledger
    {
        "id": "fact_forensic_ledger_surface",
        "domain": DomainCategory.V_FORENSIC_LEDGER,
        "title": "Forensic Ledger & Evidence Reconstruction",
        "fact_statement": "The Forensic Ledger provides transaction search/filtering, chronological lifecycle reconstruction (seq_id ASC), cryptographic SHA-256 proof hash verification, and JSON evidence export.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["frontend/src/features/forensics/ForensicLedger.tsx"],
        "rationale": "ForensicLedger.tsx component implementation.",
        "is_dynamic_tool_required": False,
    },
    # Domain W: Developer Wire Telemetry
    {
        "id": "fact_wire_telemetry_surface",
        "domain": DomainCategory.W_DEVELOPER_WIRE_TELEMETRY,
        "title": "Developer Wire Protocol Drawer",
        "fact_statement": "The Developer Wire drawer inspects raw HTTP traffic, endpoint paths, method, HTTP status, request/response JSON payloads, and execution latency.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["frontend/src/features/telemetry/DeveloperWireDrawer.tsx"],
        "rationale": "DeveloperWireDrawer.tsx implementation.",
        "is_dynamic_tool_required": False,
    },
    # Domain X: Conversational Interface
    {
        "id": "fact_conversational_interface_shell",
        "domain": DomainCategory.X_CONVERSATIONAL_INTERFACE,
        "title": "The Voice of Trust Conversational Drawer",
        "fact_statement": "The conversational interface provides a sliding drawer with animated voice waveform visualizer, intent execution feedback, quick action suggestions, and text/mic input.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_2_SOURCE_CODE,
        "verified_sources": ["frontend/src/features/conversational/ConversationalVoiceDrawer.tsx", "frontend/src/features/conversational/VoiceWaveformVisualizer.tsx"],
        "rationale": "Conversational UI components in frontend.",
        "is_dynamic_tool_required": False,
    },
    # Domain Y: Test Suites
    {
        "id": "fact_test_suite_verification",
        "domain": DomainCategory.Y_TEST_SUITES,
        "title": "Test Suite Architecture and Proof Coverage",
        "fact_statement": "The project test suite includes unit policy engine tests (100% coverage of reason codes), endpoint unit tests, integration E2E tests for Razorpay and audit chaining, and automated Phase 4 & 5 verification scripts.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_4_AUTOMATED_TESTS,
        "verified_sources": ["backend/tests/unit/", "backend/tests/integration/", "scripts/verify_phase5.py"],
        "rationale": "Verified by running pytest suite.",
        "is_dynamic_tool_required": False,
    },
    # Domain Z: Design Decisions
    {
        "id": "fact_design_decisions_yagni",
        "domain": DomainCategory.Z_DESIGN_DECISIONS,
        "title": "Lean Architecture & Anti-Bloat Invariants",
        "fact_statement": "AgentGuard explicitly avoids vector databases or LangGraph in the core authorization engine, keeping the firewall purely deterministic, stateless, and ACID-backed by PostgreSQL.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_5_SPEC_DOCS,
        "verified_sources": ["docs/Architecture.md", "docs/PRD.md"],
        "rationale": "Documented in PRD.md §8 Non-Goals.",
        "is_dynamic_tool_required": False,
    },
    # Domain AA: Technology Choices
    {
        "id": "fact_tech_choices_postgres_rationale",
        "domain": DomainCategory.AA_TECHNOLOGY_CHOICES,
        "title": "PostgreSQL Selection Rationale",
        "fact_statement": "PostgreSQL was chosen specifically over NoSQL stores because ACID transactions and atomic row-level locks are strictly required to prevent concurrent double-spending in autonomous commerce.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_5_SPEC_DOCS,
        "verified_sources": ["docs/TRD.md"],
        "rationale": "Documented in TRD.md §1 Tech Stack.",
        "is_dynamic_tool_required": False,
    },
    # Domain AB: Limitations
    {
        "id": "fact_scope_limitations",
        "domain": DomainCategory.AB_LIMITATIONS,
        "title": "System Scope Limitations",
        "fact_statement": "AgentGuard is an authorization firewall for commerce transactions; it does not handle physical product shipment, warehouse logistics, or real-money banking transactions (runs test-mode only).",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_5_SPEC_DOCS,
        "verified_sources": ["docs/PRD.md", "docs/threat_model.md"],
        "rationale": "Outlined in threat model out-of-scope boundaries.",
        "is_dynamic_tool_required": False,
    },
    # Domain AC: Future Roadmap
    {
        "id": "fact_future_roadmap",
        "domain": DomainCategory.AC_FUTURE_ROADMAP,
        "title": "Future Architectural Roadmap",
        "fact_statement": "Future iterations plan support for multi-mandate sub-agent delegation, biometric hardware token human approvals, webhook event streams, and production payment gateways.",
        "authority": AuthorityType.HISTORICAL,
        "source_tier": SourceTier.TIER_5_SPEC_DOCS,
        "verified_sources": ["docs/PRD.md"],
        "rationale": "Documented in PRD roadmap section.",
        "is_dynamic_tool_required": False,
    },
    # Domain AD: Hackathon Demo Workflow
    {
        "id": "fact_demo_pitch_workflow",
        "domain": DomainCategory.AD_HACKATHON_DEMO_WORKFLOW,
        "title": "3-Minute Hackathon Demo Progression",
        "fact_statement": "The demo workflow follows: (1) Introduce untrusted AI agent problem, (2) Trigger live price tampering attack in Threat Lab, (3) Show firewall DENY verdict in Live Defense, (4) Inspect verified SHA-256 hash link in Forensic Ledger.",
        "authority": AuthorityType.AUTHORITATIVE,
        "source_tier": SourceTier.TIER_5_SPEC_DOCS,
        "verified_sources": ["docs/Architecture.md", "docs/seed_data.md"],
        "rationale": "Standard hackathon presentation journey.",
        "is_dynamic_tool_required": False,
    },
]


class CanonicalFactsBuilder:
    """Builds authoritative canonical facts and evaluates domain coverage."""

    @classmethod
    def build_facts(cls) -> tuple[list[CanonicalFactRecord], list[KnowledgeUnit]]:
        """Constructs canonical fact records and converts them to KnowledgeUnits."""
        fact_records: list[CanonicalFactRecord] = []
        units: list[KnowledgeUnit] = []

        for item in CANONICAL_FACTS_DATA:
            rec = CanonicalFactRecord(
                id=item["id"],
                domain=item["domain"],
                title=item["title"],
                fact_statement=item["fact_statement"],
                authority=item["authority"],
                source_tier=item["source_tier"],
                rationale=item["rationale"],
                verified_sources=item["verified_sources"],
                is_dynamic_tool_required=item["is_dynamic_tool_required"],
                required_tool=item.get("required_tool"),
            )
            fact_records.append(rec)

            content_hash = hashlib.sha256(rec.fact_statement.encode("utf-8")).hexdigest()

            unit = KnowledgeUnit(
                id=f"fact_{rec.id}",
                domain=rec.domain,
                title=rec.title,
                summary=rec.fact_statement,
                content=(
                    f"Canonical Fact: {rec.title}\n"
                    f"Domain: {rec.domain.value}\n"
                    f"Authority: {rec.authority.value}\n"
                    f"Statement: {rec.fact_statement}\n"
                    f"Rationale: {rec.rationale}\n"
                    f"Verified Sources: {', '.join(rec.verified_sources)}\n"
                    f"Dynamic Tool Required: {'Yes (' + str(rec.required_tool) + ')' if rec.is_dynamic_tool_required else 'No (Static Fact)'}"
                ),
                source_type="CANONICAL_FACT",
                source_path=rec.verified_sources[0] if rec.verified_sources else "canonical/facts.json",
                source_tier=rec.source_tier,
                line_start=None,
                line_end=None,
                symbol=None,
                route=None,
                content_sha256=content_hash,
                authority=rec.authority,
                freshness=FreshnessStatus.VERIFIED,
                relationships=[],
                tags=["canonical_fact", rec.domain.value.lower()],
                dynamic_tool_fallback=rec.required_tool,
            )
            units.append(unit)

        return fact_records, units

    @classmethod
    def evaluate_domain_coverage(cls, all_units: list[KnowledgeUnit]) -> dict[str, DomainCoverageStatus]:
        """Evaluates which domains from A to AE are COVERED, PARTIALLY_COVERED, or KNOWLEDGE_GAP."""
        domain_counts: dict[DomainCategory, int] = {d: 0 for d in DomainCategory}
        for u in all_units:
            domain_counts[u.domain] = domain_counts.get(u.domain, 0) + 1

        coverage_report: dict[str, DomainCoverageStatus] = {}
        for domain, count in domain_counts.items():
            if count >= 3:
                coverage_report[domain.value] = DomainCoverageStatus.COVERED
            elif count >= 1:
                coverage_report[domain.value] = DomainCoverageStatus.PARTIALLY_COVERED
            else:
                coverage_report[domain.value] = DomainCoverageStatus.KNOWLEDGE_GAP

        return coverage_report
