from enum import Enum


class PolicyDecision(str, Enum):
    ALLOW = "ALLOW"
    ESCALATE = "ESCALATE"
    DENY = "DENY"


class ReasonCode(str, Enum):
    ALLOW = "ALLOW"
    PRICE_MISMATCH = "PRICE_MISMATCH"
    MERCHANT_MISMATCH = "MERCHANT_MISMATCH"
    QUANTITY_INVALID = "QUANTITY_INVALID"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    MANDATE_EXPIRED = "MANDATE_EXPIRED"
    MANDATE_REVOKED = "MANDATE_REVOKED"
    TRANSACTION_EXPIRED = "TRANSACTION_EXPIRED"
    REPLAY_DETECTED = "REPLAY_DETECTED"
    ALREADY_EXECUTED = "ALREADY_EXECUTED"
    ESCALATION_REQUIRED = "ESCALATION_REQUIRED"
    APPROVED_BY_HUMAN = "APPROVED_BY_HUMAN"
    REJECTED_BY_HUMAN = "REJECTED_BY_HUMAN"
    PAYMENT_DECLINED = "PAYMENT_DECLINED"
